import StyledComponentsRegistry from '@/lib/registry'
import Providers from '@/providers'
import './normalize.css'
import './styles.css'

export const metadata = {
  title: 'Be Ad',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        style={{ overflowX: 'hidden' }}
      >
        <StyledComponentsRegistry>
          <Providers>
            {children}
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
